# Generated by Django 5.2 on 2025-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailWag_Supply_app', '0002_alter_customer_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_state',
            field=models.CharField(choices=[('kerala', 'Kerala'), ('karnataka', 'Karnataka'), ('tamil_nadu', 'Tamil Nadu'), ('andhra_pradesh', 'Andhra Pradesh'), ('telangana', 'Telangana'), ('maharashtra', 'Maharashtra'), ('gujarat', 'Gujarat'), ('rajasthan', 'Rajasthan'), ('uttar_pradesh', 'Uttar Pradesh'), ('madhya_pradesh', 'Madhya Pradesh'), ('bihar', 'Bihar'), ('west_bengal', 'West Bengal'), ('punjab', 'Punjab'), ('odisha', 'Odisha')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_city',
            field=models.CharField(max_length=30),
        ),
    ]
