# Generated by Django 5.2 on 2025-04-25 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailWag_Supply_app', '0003_customer_customer_state_alter_customer_customer_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=30, null=True)),
                ('product_category', models.CharField(choices=[('FOOD', 'Food'), ('TOYS', 'Toys'), ('COLLARS', 'Collars'), ('BEDS', 'Beds'), ('GROOMING', 'Grooming'), ('CLOTHING', 'Clothing')], max_length=20)),
                ('product_price', models.CharField(max_length=10)),
                ('product_img', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('product_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.seller')),
            ],
        ),
    ]
