# Generated by Django 5.2 on 2025-06-13 10:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailWag_Supply_app', '0003_customer_customer_state_alter_customer_customer_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('messages', models.CharField(max_length=300)),
                ('replay', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=30, null=True)),
                ('product_category', models.CharField(choices=[('FOOD', 'Food'), ('TOYS', 'Toys'), ('COLLARS', 'Collars'), ('BEDS', 'Beds'), ('GROOMING', 'Grooming'), ('CLOTHING', 'Clothing')], max_length=20)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_img', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('product_count', models.IntegerField(default=0)),
                ('product_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.seller')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.product_s')),
            ],
        ),
        migrations.CreateModel(
            name='Buynow_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('choice', models.CharField(blank=True, choices=[('pending', 'Pending'), ('packed', 'Packed'), ('shifted', 'Shifted'), ('arrived', 'Arrived')], default='pending', max_length=10, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.seller')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.product_s')),
            ],
        ),
    ]
