# Generated by Django 5.2 on 2025-05-06 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailWag_Supply_app', '0004_product_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.product_s')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.customer')),
            ],
        ),
    ]
