# Generated by Django 5.2 on 2025-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailWag_Supply_app', '0005_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_s',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
