# Generated by Django 5.2 on 2025-05-28 13:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailWag_Supply_app', '0006_alter_product_s_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buynow_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.product_s')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailWag_Supply_app.seller')),
            ],
        ),
    ]
