# Generated by Django 5.2 on 2025-05-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailWag_Supply_app', '0007_buynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buynow',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
