# Generated by Django 5.2 on 2025-06-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailWag_Supply_app', '0007_buynow_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_s',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
