# Generated by Django 5.2 on 2025-06-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailWag_Supply_app', '0008_product_s_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
